version: '3'
services:

  rdbms:
    build: rdbms

  ingestion:
    build: ingestion
    links:
      - rdbms
    depends_on:
      - rdbms
    ports:
      - "8080:8080"

  sql-etl:
    build: sql-etl
    links:
      - rbdms
    depends_on:
      -rbdms



